import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
MONGODB_URI = os.getenv("MONGODB_URI")
ADMIN_SECRET_KEY = os.getenv("ADMIN_SECRET_KEY")
ADMIN_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ADMIN_ACCESS_TOKEN_EXPIRE_MINUTES", 60))
DEV_SECRET_KEY = os.getenv("DEV_SECRET_KEY")
FORGOT_PASSWORD_SECRET_KEY = os.getenv("FORGOT_PASSWORD_SECRET_KEY")
FORGOT_PASSWORD_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("FORGOT_PASSWORD_ACCESS_TOKEN_EXPIRE_MINUTES", 15))